name: "Deploy to S3"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Updates the package lists
        run: sudo apt update
      - name: Install Python3
        run: sudo apt install -y python3-pip
      - name: Install Jinja2 of version 2.10.2
        run: pip3 install --upgrade jinja2==2.10.2
      - name: Install MkDocs
        run: pip3 install mkdocs==1.3.0
      - name: Check MkDocs
        run: pip3 freeze | grep mkdocs
      - name: Install one MkDocs plugin
        run: pip3 install mkdocs-awesome-pages-plugin==2.7.0
      - name: Check that one MkDocs plugin
        run: pip3 freeze | grep -i mkdocs
      - name: Install MkDocs plugins
        run: pip3 install -r requirements.txt
      - name: List installed packages
        run: pip3 freeze
      - name: Build website
        run: mkdocs build -f documentation/mkdocs.yml
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: eu-central-1
      - name: Check folder structure
        run: pwd && ls -lh
      #- name: Copy over to S3
      #  run: aws s3 sync ./build/. s3://solver-ai-suite-mkdocs/solver-ai-suite-documentation/